# Romeo & Juliet Model Configuration - Fast Training
# Usage: python agi2_train.py resources/rj.toml

# Training data sources - list of corpus files
sources = [
    "samples/romeo_juliette.txt",
    "resources/training/corpus20.txt"
]


model_name = "rj"
model_path = "trained/rj.pt"

# Training parameters - optimized for speed
epochs = 100
batch_size = 24
learning_rate = 5e-4
seq_len = 512

# Model architecture - smaller for faster training
model_positions = 512
model_embd = 384
model_layer = 6
model_head = 6

# Device and resume options
device = "auto"
resume = ""

# Generation parameters
max_length = 300
temperature = 0.8
beam_size = 3
model_seed = """
In Verona, where the bells toll for vespers and the marketplace bustles
 with gossip and wine, entangled in a love so perilous it
 could undo the very house that raised them.
"""

# Interactive parameters
max_context_length = 512
